const airports = [['Brasília','DF','BSB'],['São Paulo','SP','GRU'],['São Paulo','SP','CGH'],['Rio de Janeiro','RJ','GIG'],['Rio de Janeiro','RJ','SDU'],['Belo Horizonte','MG','CNF'],['Salvador','BA','SSA'],['Recife','PE','REC'],['Fortaleza','CE','FOR'],['Curitiba','PR','CWB'],['Porto Alegre','RS','POA'],['Florianópolis','SC','FLN'],['Manaus','AM','MAO'],['Belém','PA','BEL'],['Goiânia','GO','GYN'],['Vitória','ES','VIX'],['Natal','RN','NAT'],['João Pessoa','PB','JPA'],['Maceió','AL','MCZ'],['Foz do Iguaçu','PR','IGU'],['Campo Grande','MS','CGR'],['Cuiabá','MT','CGB'],['Santiago','Chile','SCL'],['Buenos Aires','Argentina','EZE'],['Lisboa','Portugal','LIS'],['Miami','Estados Unidos','MIA'],['Orlando','Estados Unidos','MCO'],['Paris','França','CDG'],['Londres','Reino Unido','LHR'],['Nova York','Estados Unidos','JFK']];
const grid=document.querySelector('#routes-grid'),count=document.querySelector('#route-count'),message=document.querySelector('#form-message'),apiStatus=document.querySelector('#api-status');let selectedRouteId=null;
const money=(v,c='BRL')=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(Number(v));
const date=v=>new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:'short',year:'numeric'}).format(new Date(v));
const normalise=v=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
document.querySelector('#data-ida').min=new Date().toISOString().slice(0,10);
async function request(path,options={}){const response=await fetch(`/api${path}`,{headers:{'Content-Type':'application/json',...options.headers},...options});const body=response.status===204?null:await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.message||'Não foi possível concluir esta ação.');return body}
function setupAirportSearch(name,listId){const input=document.querySelector(`[name="${name}"]`),list=document.querySelector(listId);const choose=a=>{input.value=`${a[0]} (${a[2]})`;input.dataset.iata=a[2];list.classList.remove('visible')};const show=()=>{const term=normalise(input.value.trim());if(!term){list.classList.remove('visible');return}const matches=airports.filter(a=>a.some(v=>normalise(v).includes(term))).slice(0,6);list.innerHTML=matches.map((a,i)=>`<button class="suggestion" type="button" data-index="${i}"><span>${a[0]}, ${a[1]}</span><code>${a[2]}</code></button>`).join('');list.classList.toggle('visible',matches.length>0);list.querySelectorAll('button').forEach(b=>b.addEventListener('mousedown',e=>{e.preventDefault();choose(matches[b.dataset.index])}))};input.addEventListener('input',()=>{delete input.dataset.iata;show()});input.addEventListener('focus',show);input.addEventListener('blur',()=>setTimeout(()=>list.classList.remove('visible'),120))}
setupAirportSearch('origem','#origin-suggestions');setupAirportSearch('destino','#destination-suggestions');
function status(state,text){apiStatus.className=`api-status ${state}`;apiStatus.querySelector('span').textContent=text}
function render(routes){count.textContent=routes.length;if(!routes.length){grid.innerHTML='<div class="empty-state"><span>⌁</span><h3>Nenhuma rota ainda</h3><p>Cadastre uma rota para começar a acompanhar os preços.</p></div>';return}grid.innerHTML=routes.map(r=>{const p=r.historicos?.[0];return `<article class="route-card ${r.ativa?'':'inactive'}"><div class="card-top"><div class="route-code">${r.origem}<span>→</span>${r.destino}</div><span class="badge">${r.ativa?'ATIVA':'PAUSADA'}</span></div><p class="dates">${date(r.dataIda)}${r.dataVolta?` — ${date(r.dataVolta)}`:' · somente ida'}</p><div class="price-line"><div><div class="price-label">ÚLTIMA TARIFA</div><div class="price ${p?'':'empty'}">${p?money(p.preco,p.moeda):'Aguardando coleta'}</div></div>${p?`<span class="price-label">${p.companhia}</span>`:''}</div><div class="card-actions"><button data-action="history" data-id="${r.id}">Histórico</button><button data-action="alert" data-id="${r.id}" data-route="${r.origem} → ${r.destino}">Alerta</button><button data-action="toggle" data-id="${r.id}" data-active="${r.ativa}">${r.ativa?'Pausar':'Reativar'}</button></div></article>`}).join('')}
async function load(){grid.innerHTML='<div class="loading">Carregando suas rotas…</div>';try{const routes=await request('/rotas');const withPrices=await Promise.all(routes.map(async r=>({...r,historicos:await request(`/rotas/${r.id}/historico`).catch(()=>[])})));status('online','API conectada');render(withPrices)}catch{status('offline','API indisponível');grid.innerHTML='<div class="empty-state"><span>!</span><h3>Não foi possível acessar a API</h3><p>Inicie o backend em <code>http://localhost:3000</code> e tente novamente.</p></div>'}}
document.querySelector('#route-form').addEventListener('submit',async e=>{e.preventDefault();message.textContent='';const form=e.currentTarget,origem=form.elements.origem.dataset.iata,destino=form.elements.destino.dataset.iata;if(!origem||!destino){message.textContent='Escolha uma cidade nas sugestões para origem e destino.';return}const body=Object.fromEntries(new FormData(form)),button=form.querySelector('.primary-button');body.origem=origem;body.destino=destino;if(!body.dataVolta)delete body.dataVolta;if(body.dataVolta&&body.dataVolta<body.dataIda){message.textContent='A data de volta não pode ser anterior à ida.';return}button.disabled=true;button.textContent='Salvando…';try{await request('/rotas',{method:'POST',body:JSON.stringify(body)});form.reset();delete form.elements.origem.dataset.iata;delete form.elements.destino.dataset.iata;message.textContent='Rota cadastrada e monitorada!';await load()}catch(err){message.textContent=err.message}finally{button.disabled=false;button.innerHTML='Monitorar rota <span>→</span>'}});
grid.addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const{action,id}=b.dataset;if(action==='history')return history(id);if(action==='alert'){selectedRouteId=id;document.querySelector('#alert-title').textContent=`Meta para ${b.dataset.route}`;document.querySelector('#alert-message').textContent='';document.querySelector('#target-price').value='';document.querySelector('#alert-dialog').showModal();return}b.disabled=true;try{await request(`/rotas/${id}/${b.dataset.active==='true'?'desativar':'reativar'}`,{method:'PATCH'});await load()}catch(err){alert(err.message);b.disabled=false}});
async function history(id){const dialog=document.querySelector('#history-dialog'),content=document.querySelector('#history-content');dialog.showModal();content.innerHTML='<p class="loading">Carregando histórico…</p>';try{const h=await request(`/rotas/${id}/historico`);content.innerHTML=h.length?`<div class="history-list">${h.map(x=>`<div class="history-row"><div><strong>${money(x.preco,x.moeda)}</strong><p>${x.companhia}</p></div><time>${new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x.coletadoEm))}</time></div>`).join('')}</div>`:'<p class="history-empty">Ainda não há preços coletados para esta rota.</p>'}catch(err){content.innerHTML=`<p class="history-empty">${err.message}</p>`}}
document.querySelectorAll('.close-button').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelector('#alert-form').addEventListener('submit',async e=>{e.preventDefault();try{await request(`/rotas/${selectedRouteId}/alerta-preco`,{method:'PUT',body:JSON.stringify({precoAlvo:document.querySelector('#target-price').value.trim().replace(',','.')})});document.querySelector('#alert-dialog').close()}catch(err){document.querySelector('#alert-message').textContent=err.message}});document.querySelector('#check-prices').addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Atualizando…';try{await request('/rotas/verificar-precos',{method:'POST'});await load()}catch(err){alert(err.message)}finally{b.disabled=false;b.textContent='Atualizar preços ↻'}});load();
